### PR TITLE
deleted Gemfile.lock and added to .gitignore

### PR DESCRIPTION
**Pull request by JustinDevelops**

### CODE REVIEW

**Comment by BenRuns** [comment]
Did this solve the Debian installation issues?

**Comment by JustinDevelops** [comment]
Not quite sure yet. Still working on installing RVM the right way. I had it all wrong, haha. But I saw the lock file and wanted to get it out of repo.

**Comment by BenRuns** [comment]
Well, the internet seemed mixed on whether or not it should be checked in or not and I don't have a strong opinion on it.

**Comment by gekitsuu** [comment]
Typically you check it in so the versions of libs that your developing against stays where you want them until you are ready to update them. For example if you were running a build in circle ci but one of the libs had updated with a breaking change since you installed them locally, the build would break. By pinning the version everyone everywhere is building with the same versions

**Comment by JustinDevelops** [comment]
@gekitsuu So we should probably revert that since @BenRuns  is the one that set this up and that was his Gemfile.lock file?

**Comment by BenRuns** [comment]
I'm for reverting the merge.  I don't have backup for it causing issues in local development on different systems. Can revisit if removing it solves the Debian install issues

**Pull request merged**
